### ISSUE TITLE
KuCoinApi.Net v2.0 doesn't work with RESTApiAccess v 1.3.0

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.Net#12]
Dear developer,
today I download from nuget KuCoinApi.Net (0.3.0) and error occurs during debug my app:
MissingMethodException: Method not found: "System.Threading.Tasks.Task`1<!!0> RESTApiAccess.Interface.IRESTRepository.GetApiStream(System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>)".

I downgraded verison of RESTApiAccess from 1.3.0 to 1.2.1 and app works now. Please, fix this issue.

**Comment by mscheetz** [comment]
Think i found the issue in RestApiAccess, just updated it.  Which endpoints were giving you errors?

**Comment by SergeevGregory** [comment]
Main constructor of KuCoinApi give this error. I tested new RESTApiAccess (v 1.3.1) and nothing new... Again not work.

**Comment by mscheetz** [comment]
Updated this KuCoin library, should be working now with the new RESTApiAccess
