### ISSUE TITLE
Exception: {"code":"400005","msg":"Invalid KC-API-SIGN"} 

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.Net#13]
Dear developer,
today I tested new feature of version 0.3.0 - GetPrivateChannels. It doesn't work:
Exception: {"code":"400005","msg":"Invalid KC-API-SIGN"}

Other functions like GetBalances work good. Please, fix this issue :)

**Comment by mscheetz** [comment]
Left a message on the KuCoin API Telegram, this is the only endpoint throwing this error.

Lets see what they say.

**Comment by SergeevGregory** [comment]
Same issue with PlaceLimitOrder… :(

**Comment by mscheetz** [comment]
I'll take a look tonight

**Comment by SergeevGregory** [comment]
Dear Matt, 
I found problem in GetPrivateChannels (with help of Reeta).

Problem is in KucoinAPITest in string:
`var content = new StringContent(JsonConvert.SerializeObject(data), Encoding.UTF8, "application/json");`
to fix it, replace this string to:
`var content = new StringContent(data == null ? "" : JsonConvert.SerializeObject(data), Encoding.UTF8, "application/json");`

It occurs because JsonConvert.SerializeObject(null) is "null", not "".

GetPrivateChannels works with this fix, **but PlaceLimitOrder doesn't not work** :(
