### ISSUE TITLE
Get fills params issue

### ISSUE THREAD

**Issue by dangth92** [mscheetz/KuCoinApi.Net#6]
I tried to get list fills with request parameters:

* startAt = 1550595600000
* endAt = 1550768399000

The reponse content is a message "Get List Fills doesn't support get fills in a large timespan (> 24 hours)" with code "400100"

**Comment by mscheetz** [comment]
Looks like this is something built into the api, probably to limit the amount of data being transferred via a rest request. If you check out the telegram channel: https://t.me/KuCoin_API this looks to be happening to others. I would suggest dropping your timespan to less than 24hours as the error message suggests.
