### ISSUE TITLE
Many endpoints/parameters are wrong

### ISSUE THREAD

**Issue by yukseljunk** [mscheetz/KuCoinApi.Net#8]
Hi,
thx for effort, but I always need to figure out the correct endpoints, because almost none of them works, i.e. /timestamp instead of v1/time, and then fails on getbalance. Has kucoin changed these during their new API development?

**Comment by mscheetz** [comment]
Are you looking at the new v2.0 branch? https://github.com/mscheetz/KuCoinApi.Net/tree/v2.0
