### ISSUE TITLE
Please, add GetAllTickers

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.Net#9]
Dear developer,
please, add GetAllTickers function (GET /api/v1/market/allTickers) for v2 branch.

Thank you.

**Comment by mscheetz** [comment]
I'll take a look at it later today.

**Comment by mscheetz** [comment]
Thanks for catching this. It is added.

**Comment by SergeevGregory** [comment]
Please, add buy and sell to TradingPairStats :)

**Comment by mscheetz** [comment]
This one got added on Monday.
